--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ClickedTran/libScriptAPIPlugin
build-by-default: true
branches:
- Master
projects:
  libScriptAPIPlugin:
    path: ""
    libs:
     - src: jojoe77777/FormAPI/libFormAPI
       version: ^2.1.1
     - src: muqsit/InvMenu/InvMenu
       version: ^4.6.6
     - src: ClickedTran/libScriptAPI/libScriptAPI
      version: 1.0.0-BETA
...
